version: '3.8'

services:
  serving-api:
    container_name: serving-api
    build: ./serving
    ports:
      - "8080:8080"
    volumes:
      - ./artifacts:/artifacts
      - ./data:/data

  webapp:
    container_name: webapp
    build: ./webapp
    ports:
      - "8501:8501"
    depends_on:
      - serving-api

  reporting:
    container_name: reporting
    build: ./reporting
    ports:
      - "8082:8082"
    volumes:
      - ./data:/data